/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LainnyaRouteImport } from './routes/lainnya'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as MutasiRouteImport } from './routes/mutasi'
import { Route as PembelianRouteImport } from './routes/pembelian'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PengeluaranRouteImport } from './routes/pengeluaran'
import { Route as PenjualanRouteImport } from './routes/penjualan'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as StokRouteImport } from './routes/stok'
import { Route as BahanIndexRouteImport } from './routes/bahan.index'
import { Route as BahanIdRouteImport } from './routes/bahan.$id'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaRoute = LainnyaRouteImport.update({
  id: '/lainnya',
  path: '/lainnya',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const MutasiRoute = MutasiRouteImport.update({
  id: '/mutasi',
  path: '/mutasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PembelianRoute = PembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranRoute = PengeluaranRouteImport.update({
  id: '/pengeluaran',
  path: '/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualanRoute = PenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const BahanIndexRoute = BahanIndexRouteImport.update({
  id: '/bahan/',
  path: '/bahan/',
  getParentRoute: () => rootRouteImport,
} as any)
const BahanIdRoute = BahanIdRouteImport.update({
  id: '/bahan/$id',
  path: '/bahan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lainnya': typeof LainnyaRoute
  '/laporan': typeof LaporanRoute
  '/mutasi': typeof MutasiRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/penjualan': typeof PenjualanRoute
  '/riwayat': typeof RiwayatRoute
  '/stok': typeof StokRoute
  '/bahan/$id': typeof BahanIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/bahan/': typeof BahanIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lainnya': typeof LainnyaRoute
  '/laporan': typeof LaporanRoute
  '/mutasi': typeof MutasiRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/penjualan': typeof PenjualanRoute
  '/riwayat': typeof RiwayatRoute
  '/stok': typeof StokRoute
  '/bahan/$id': typeof BahanIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/bahan': typeof BahanIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lainnya': typeof LainnyaRoute
  '/laporan': typeof LaporanRoute
  '/mutasi': typeof MutasiRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/penjualan': typeof PenjualanRoute
  '/riwayat': typeof RiwayatRoute
  '/stok': typeof StokRoute
  '/bahan/$id': typeof BahanIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/bahan/': typeof BahanIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lainnya'
    | '/laporan'
    | '/mutasi'
    | '/pembelian'
    | '/pengaturan'
    | '/pengeluaran'
    | '/penjualan'
    | '/riwayat'
    | '/stok'
    | '/bahan/$id'
    | '/produk/$id'
    | '/bahan/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lainnya'
    | '/laporan'
    | '/mutasi'
    | '/pembelian'
    | '/pengaturan'
    | '/pengeluaran'
    | '/penjualan'
    | '/riwayat'
    | '/stok'
    | '/bahan/$id'
    | '/produk/$id'
    | '/bahan'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/lainnya'
    | '/laporan'
    | '/mutasi'
    | '/pembelian'
    | '/pengaturan'
    | '/pengeluaran'
    | '/penjualan'
    | '/riwayat'
    | '/stok'
    | '/bahan/$id'
    | '/produk/$id'
    | '/bahan/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LainnyaRoute: typeof LainnyaRoute
  LaporanRoute: typeof LaporanRoute
  MutasiRoute: typeof MutasiRoute
  PembelianRoute: typeof PembelianRoute
  PengaturanRoute: typeof PengaturanRoute
  PengeluaranRoute: typeof PengeluaranRoute
  PenjualanRoute: typeof PenjualanRoute
  RiwayatRoute: typeof RiwayatRoute
  StokRoute: typeof StokRoute
  BahanIdRoute: typeof BahanIdRoute
  ProdukIdRoute: typeof ProdukIdRoute
  BahanIndexRoute: typeof BahanIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya': {
      id: '/lainnya'
      path: '/lainnya'
      fullPath: '/lainnya'
      preLoaderRoute: typeof LainnyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutasi': {
      id: '/mutasi'
      path: '/mutasi'
      fullPath: '/mutasi'
      preLoaderRoute: typeof MutasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembelian': {
      id: '/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof PembelianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran': {
      id: '/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof PengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjualan': {
      id: '/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof PenjualanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bahan/': {
      id: '/bahan/'
      path: '/bahan'
      fullPath: '/bahan/'
      preLoaderRoute: typeof BahanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bahan/$id': {
      id: '/bahan/$id'
      path: '/bahan/$id'
      fullPath: '/bahan/$id'
      preLoaderRoute: typeof BahanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LainnyaRoute: LainnyaRoute,
  LaporanRoute: LaporanRoute,
  MutasiRoute: MutasiRoute,
  PembelianRoute: PembelianRoute,
  PengaturanRoute: PengaturanRoute,
  PengeluaranRoute: PengeluaranRoute,
  PenjualanRoute: PenjualanRoute,
  RiwayatRoute: RiwayatRoute,
  StokRoute: StokRoute,
  BahanIdRoute: BahanIdRoute,
  ProdukIdRoute: ProdukIdRoute,
  BahanIndexRoute: BahanIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
